image: node:lts

stages:
  - build
  - deploy

variables:
  GIT_DEPTH: 1
  PNPM_HOME: $CI_PROJECT_DIR/.pnpm

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store

build:
  environment:
    name: staging1
  when: manual
  only:
    - main
    - staging3
    - deploy
  tags:
    - runner1
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install --store .pnpm-store
    - echo "SERVER_URL=$SERVER_URL" > .env
    - pnpm build
    - ls -la build/
  artifacts:
    paths:
      - build/
      - package.json
      - pnpm-lock.yaml
    expire_in: 1 week

deploy:
  environment:
    name: staging1
  tags:
    - runner1
  stage: deploy
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  only:
    - staging3
    - deploy
  before_script:
#    - apk add --no-cache openssh-client dos2unix
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
#    - dos2unix ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 38.180.163.160 >> ~/.ssh/known_hosts
#    - ssh dev@38.180.163.160 "curl -fsSL https://get.pnpm.io/install.sh | sh -"
#    - ssh dev@38.180.163.160 "export PNPM_HOME=\"\$HOME/.local/share/pnpm\" && export PATH=\"\$PNPM_HOME:\$PATH\" && \
#      cd /var/www/understat/frontend && \
  script:
    - ls -l ~/.ssh/id_rsa
    - ssh-keygen -yf ~/.ssh/id_rsa > /dev/null
    - ssh -v dev@38.180.163.160 "echo 'SSH connection successful'"
    - scp -r build/* dev@38.180.163.160:/var/www/understat/frontend
    - scp package.json pnpm-lock.yaml dev@38.180.163.160:/var/www/understat/frontend/
    - ssh dev@38.180.163.160 "source /home/dev/.nvm/nvm.sh && cd /var/www/understat/frontend && pnpm install --store .pnpm-store"
    - scp nginx.conf dev@38.180.163.160:/home/dev/
    - ssh dev@38.180.163.160 "pm2 reload sveltekit-app || pm2 start build/index.js --name sveltekit-app"
    - ssh dev@38.180.163.160 "ls -la /home/dev/nginx.conf"
    - ssh dev@38.180.163.160 "sudo mv /home/dev/nginx.conf /etc/nginx/sites-available/dev.sntmq.1keep.bet"
    - ssh dev@38.180.163.160 'sudo ln -sf /etc/nginx/sites-available/dev.sntmq.1keep.bet /etc/nginx/sites-enabled/dev.sntmq.1keep.bet'
    - ssh dev@38.180.163.160 'sudo systemctl reload nginx'
